(lang dune 2.0)

(name k98)





(license ISC)

(authors
  "useada")

(maintainers
  "useada")

(generate_opam_files true)

(package
 (name k98)
 (synopsis "quant")
 (description "quant")
 (depends
  (ocaml (>= 4.12.0))
  dune
  (alcotest :with-test)
  (odoc :with-doc)))
